---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "ui.fullname" . }}
#  annotations:
#    kubernetes.io/ingress.class: "gce"
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: {{ template "ui.fullname" . }}
            port:
              number: 9292
