version: '3.3'
services:
  mongo:
    container_name: mongo_db
    image: mongo
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
  ui:
    container_name: ui
    build: ./ui
    image: ${USERNAME}/ui:${UI_VERSION}
    command: "puma --debug -w 2"
    ports:
      - ${UI_PORT}:9292/tcp
    volumes:
      - "./ui:/app"
    networks:
      - front_net
    depends_on:
      - mongo
      - post
      - comment
  post:
    container_name: post
    build: ./post-py
    image: ${USERNAME}/post:${POST_VERSION}
    volumes:
      - "./post-py:/app"
    networks:
      - back_net
      - front_net
    depends_on:
      - mongo
  comment:
    container_name: comment
    build: ./comment
    image: ${USERNAME}/comment:${COMMENT_VERSION}
    volumes:
      - "./comment:/app"
    networks:
      - back_net
      - front_net
    depends_on:
      - mongo


volumes:
  post_db:

networks:
  back_net:
    name: back_net
  front_net:
    name: front_net
