- hosts: all
  become: true

  tasks:
  - name: install apt dependencies
    apt:
      name: "{{item}}"
      state: present
      update_cache: yes
    with_items:
      - ca-certificates
      - curl
      - gnupg-agent

  - name: add GPG key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: add docker repository to apt
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu bionic stable
      state: present  

  - name: install docker
    apt:
      name: "{{item}}"
      state: latest
      update_cache: yes
    loop:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin 
      - docker-compose-plugin
      - python3-docker

  - name: Add group docker
    ansible.builtin.group:
      name: docker
      state: present
  
  - name: Add user to docker group
    user:
      name: ubuntu
      groups: docker
      append: yes